# Generated by Django 5.2.8 on 2026-05-10 02:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('provider', models.CharField(default='paystack', max_length=50)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('channel', models.CharField(blank=True, choices=[('card', 'Card'), ('bank', 'Bank'), ('ussd', 'Ussd'), ('transfer', 'Transfer'), ('qr', 'Qr'), ('mobile_money', 'Mobile Money')], max_length=50, null=True)),
                ('authorization_url', models.URLField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='authentication.driverprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['driver', 'payment_date'], name='payments_pa_driver__c2b923_idx'), models.Index(fields=['reference'], name='payments_pa_referen_75358f_idx'), models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'SUCCESS')), fields=('driver', 'payment_date'), name='unique_successful_daily_payment')],
            },
        ),
    ]
