# Generated by Django 5.2.8 on 2026-03-05 05:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_authorization_url_payment_channekl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='channekl',
        ),
        migrations.AddField(
            model_name='payment',
            name='channel',
            field=models.CharField(blank=True, choices=[('card', 'Card'), ('bank', 'Bank'), ('ussd', 'Ussd'), ('transfer', 'Transfer'), ('qr', 'Qr'), ('mobile_money', 'Mobile Money')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
