# Generated by Django 5.2.8 on 2026-03-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_payment_channekl_payment_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
