# Generated by Django 5.2.8 on 2026-03-05 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_gateway_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='provider_response',
        ),
    ]
