# Generated by Django 5.2.8 on 2026-05-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_seed_lagos_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='lga',
            field=models.CharField(default='', max_length=100),
        ),
    ]
