# Generated by Django 5.2.8 on 2026-01-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
