# Generated by Django 5.2.8 on 2026-02-12 18:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocument',
            name='document_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='driver_document'),
        ),
    ]
