# Generated by Django 5.2.8 on 2026-02-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_driverdocument_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='phone_number',
            field=models.CharField(db_index=True, unique=True),
        ),
    ]
