# Generated by Django 5.2.8 on 2026-02-16 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_driverprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverprofile',
            old_name='zone',
            new_name='area',
        ),
    ]
