# Generated by Django 5.2.8 on 2026-02-20 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_driverprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='authentication.agentprofile'),
        ),
    ]
