# Generated by Django 5.2.8 on 2026-02-21 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_driverprofile_agent'),
        ('authentication', '0006_rename_zone_driverprofile_area'),
    ]

    operations = [
    ]
