# Generated by Django 5.2.8 on 2026-04-08 18:35

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_merge_20260221_0934'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='agentprofile',
            name='authenticat_is_acti_d11cdf_idx',
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_agents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='lga',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='nin_document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='agent_nin'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('pending_kyc', 'Pending KYC'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='invited', max_length=20),
        ),
        migrations.AddIndex(
            model_name='agentprofile',
            index=models.Index(fields=['status'], name='authenticat_status_b33b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='driverdocument',
            index=models.Index(fields=['status'], name='authenticat_status_6b227e_idx'),
        ),
        migrations.AddIndex(
            model_name='driverdocument',
            index=models.Index(fields=['verified'], name='authenticat_verifie_194592_idx'),
        ),
    ]
