# Generated by Django 5.2.8 on 2026-04-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_agentprofile_authenticat_is_acti_d11cdf_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='invite_token_used',
            field=models.BooleanField(default=False),
        ),
    ]
