# Generated by Django 5.2.8 on 2026-04-11 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_agentprofile_invite_token_used'),
        ('common', '0002_seed_lagos_areas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='area',
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='areas',
            field=models.ManyToManyField(blank=True, related_name='agents', to='common.area'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='common.area'),
        ),
    ]
