# Generated by Django 5.2.8 on 2026-04-11 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_agentprofile_area_agentprofile_areas_and_more'),
        ('common', '0002_seed_lagos_areas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='areas',
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='common.area'),
        ),
    ]
