# Generated by Django 5.2.8 on 2026-05-02 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_convert_area_to_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='lga',
        ),
    ]
