# Generated by Django 5.2.8 on 2026-05-02 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_remove_driverprofile_lga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='lga',
        ),
    ]
