# Generated by Django 5.2.8 on 2026-02-21 08:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0007_merge_20260221_0934'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_for_date', models.DateField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_in_area', to='authentication.driverprofile')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_tickets', to='authentication.driverprofile')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_tickets', to='payments.payment')),
            ],
            options={
                'indexes': [models.Index(fields=['ticket_number'], name='ticket_tick_ticket__0983d6_idx'), models.Index(fields=['driver'], name='ticket_tick_driver__b002b3_idx'), models.Index(fields=['area'], name='ticket_tick_area_id_93ebc2_idx'), models.Index(fields=['status'], name='ticket_tick_status_3a7aff_idx')],
            },
        ),
    ]
