# Generated by Django 5.2.8 on 2026-05-10 02:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('common', '0004_seed_area_lga'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(max_length=50, unique=True)),
                ('qr_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_for_date', models.DateField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='common.area')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_tickets', to='authentication.driverprofile')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_tickets', to='payments.payment')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_tickets', to='authentication.agentprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['ticket_number'], name='ticket_tick_ticket__0983d6_idx'), models.Index(fields=['driver'], name='ticket_tick_driver__b002b3_idx'), models.Index(fields=['status'], name='ticket_tick_status_3a7aff_idx'), models.Index(fields=['valid_for_date'], name='ticket_tick_valid_f_5ae18d_idx')],
                'constraints': [models.UniqueConstraint(fields=('payment',), name='unique_ticket_per_payment'), models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('driver', 'valid_for_date', 'area'), name='unique_active_ticket_per_driver_per_day_area')],
            },
        ),
    ]
