# Generated by Django 5.2.8 on 2026-02-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ticket',
            new_name='ticket_tick_area_b06258_idx',
            old_name='ticket_tick_area_id_93ebc2_idx',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='area',
            field=models.CharField(max_length=100),
        ),
    ]
