# Generated by Django 5.2.8 on 2026-03-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
