# Generated by Django 5.2.8 on 2026-03-03 11:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_ticket_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='qr_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
