# Generated by Django 5.2.8 on 2026-04-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_agentprofile_authenticat_is_acti_d11cdf_idx_and_more'),
        ('payments', '0007_remove_payment_provider_response'),
        ('ticket', '0006_alter_ticket_qr_code'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('payment',), name='unique_ticket_per_payment'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('driver', 'valid_for_date', 'area'), name='unique_active_ticket_per_driver_per_day_area'),
        ),
    ]
