# Generated by Django 5.2.8 on 2026-04-11 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_seed_lagos_areas'),
        ('ticket', '0007_ticket_unique_ticket_per_payment_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ticket',
            new_name='ticket_tick_area_id_93ebc2_idx',
            old_name='ticket_tick_area_b06258_idx',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='common.area'),
        ),
    ]
