# Generated by Django 5.2.8 on 2026-04-11 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_convert_area_to_fk'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ticket',
            new_name='ticket_tick_area_id_93ebc2_idx',
            old_name='ticket_tick_area_b06258_idx',
        ),
    ]
