# Generated by Django 5.2.8 on 2026-04-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_convert_area_to_fk'),
        ('common', '0002_seed_lagos_areas'),
        ('payments', '0007_remove_payment_provider_response'),
        ('ticket', '0009_remove_ticket_ticket_tick_area_b06258_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['valid_for_date'], name='ticket_tick_valid_f_5ae18d_idx'),
        ),
    ]
