# Generated by Django 5.2.8 on 2026-04-15 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_convert_area_to_fk'),
        ('ticket', '0010_ticket_ticket_tick_valid_f_5ae18d_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_tickets', to='authentication.agentprofile'),
        ),
    ]
